### ISSUE TITLE
Skype Konferenz

### ISSUE THREAD

**Issue by Phillip-W** [Phillip-W/_entwurf_vhdl_prozessor_rtl#1]
Wie wärs mit Sonntag Abend Skype Konferenz? 
Würde wieder so ca 21:00 anpeilen.

**Comment by flomaurer** [comment]
Nachdem ich da noch auf meiner Venedigtour war ist da nicht so viel drauß geworden.
Ich würd heut abend vorschlagen.
So gegen 19:00 oder 20:00

**Comment by Phillip-W** [comment]
ich wär eher für 8 bin noch sport treiben und des könnt knapp werden^^
Patrick wie siehts bei dir aus?

**Comment by Sabbuth** [comment]
BIn gerade zuhause angekommen. Acht ist okay für mich.

Grüße
Patrick
