### ISSUE TITLE
ALU

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/_entwurf_vhdl_prozessor_rtl#10]
hi jungs ich habe eine partiell funktionierende Version der Alu entworfen samt testbench... es fehlt der shifter natürlich. Den adder konnte ich bei meinen SImulationen nicht einbinden, weil er irgendein Problem bei der Auflösung eines Signales hat... bitte vervollständigen und auch testen :) ich habe keine Flags in definiert nur ein carry in der ALU, weil die anderen Flags bei den Operationen nicht berücksichtigt werden...

Grüße
PAtrick

**Comment by flomaurer** [comment]
shifter ist fertig - aber du hast was mit den Flags komisch gemacht.
Phillip wollt da mal drüber schaun und das verbessern.

**Comment by Sabbuth** [comment]
also gut gemacht flo... funktioniert super. ich habe in deinem shifter das flag in gegen ein carry in signal ersetzt, weil die alu nur ein carry in hat und keine anderen flags in signale, aber das soll kein unterschied machen... ich habe einen Befehl getestet und es funktioniert, so wie es funktionieren sollte.

Phillip schau mal bitte, dass du es hinkriegst alle signale zu resolven... mit deinem Modul kann ich deswegen gar nicht simulieren, hab in in der allu deswegen auskomentiert...

Ich werde heute oder morgen mit dem ID anfangen.

Grüße
Patrick

**Comment by Phillip-W** [comment]
also wegen der flags/carry geschichte:
so wies aussieht hast du letzten freitag nicht aufgepasst was flo und ich besprochen haben...
Wir hatten uns eigentlich darauf geeinigt, dass wir die flags immer als gesamten Vector weitergeben, damit wir einen klaren Datenpfad haben, der sich nicht verzweigt und wieder zusammenfügt.

was du mit signalen resolven meinst weiß ich leider nicht bei mir funktionierts eigentlich alles...
