### ISSUE TITLE
FlagCheck

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/_entwurf_vhdl_prozessor_rtl#19]
Hi jungs,

ich bin gerade dabei den DataPath zu schreiben. Es fehlt mir dennoch der vollständige FC er wurde nur angefangen....

**Comment by Phillip-W** [comment]
Ich sitze gerade drann, aber ich weiß leider nicht was der Input macht, 
also ich muss entweder den alu eingang oder den pc eingang auf null checken, aber ich weiß leider nicht wann ich welchen checken muss, hat da evtl jemand mehr durchblick?

**Comment by Sabbuth** [comment]
ich vermute das ist jenes select signal von dem wir gesprochen haben( im Skript heißt es FC_SEL). Das der Floh erklärt hat... das Entscheidungskriterium kommt von der FSM

**Comment by flomaurer** [comment]
Patrick hat voll recht.
also die FSM generiert ein FC_SEL Signal (S.128). Das legst du an dein FC an zum entscheiden.
Bei FC_SEL='0' musst die Alu anschließen und bei FC_SEL='1' muss musst du D_IN anlegen.

**Comment by Phillip-W** [comment]
Mercy :)
wusste nicht ob bei 0 oder 1 die alu angeschlossen wird.

**Comment by flomaurer** [comment]
du selbst hast dei FSM geschrieben und hast dabei den Code aus dem Skript für FC_SEL abgetippt ;)

**Comment by Phillip-W** [comment]
Ja aber iwie hatt ich da nen hänger...
is ja wurst passt ja jetzt alles
