### ISSUE TITLE
Heut Abend Skype?

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/_entwurf_vhdl_prozessor_rtl#20]
Hi, wie siehts bei euch heut so um 21:00 Uhr aus?
Gruß FLo

**Comment by Phillip-W** [comment]
erstmal sorry wegen freitag, da war ich schon in östereich...
ja bin heute da wegen mir gerne.

**Comment by Sabbuth** [comment]
ich bin auch dabei
