### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/_entwurf_vhdl_prozessor_rtl#24]
die ganze Verkabelung unsere CPU

**Comment by flomaurer** [comment]
Hi Patrick, wie weit bist du damit schon?
Das denk ich ist das einzige was noch fehlt - außer der Testbench.
Falls du Hilfe brauchst, ich kann am Wochenende helfen.
Gruß Flo

**Comment by Sabbuth** [comment]
Hi Jungs,

habe soeben die CPU fertig geschrieben :) Es sind aber noch ein paar Kleinigkeiten, die fehlen... Das datapath Modul ist in der CPU enthalten. 

Ich brauche, dass @Phillip-W  sich die Multiplexer anschaut und nach Status der FSM die eingänge der Multiplexer umschaltet... ich habe sie im Moment willkürlich reingeschrieben, weil ich nicht wusste, wie sie zu verschalten sind. 

Deinen FC habe ich eingebaut und ich werde übers Wochenende den Datapath testen ... ICh hoffe, dass alles stimmt...

@flomaurer  ich glaube, dass du schon mal das ganze Gehäuse machen kannst mit den zwei Multpilexer, die Fehlen, mit dem Speicher und der Peripherie..(das Toplevel Modul)

Ich habe die meisten Signale wie im SKript benannt :)

Das ganze zu testen wird bestimmt noch viel Arbeit, aber das Meiste haben wir schon hinter uns.

Ich habe auch weitere kleine Veränderungen gemacht, bitte schaut sie euch an. Es ist alles kommentiert.

Grüße 
Patrick

**Comment by flomaurer** [comment]
hab mal begonnen - und Patrick deine buffer hab ich auch weg, die sind einfach nicht schön ;)

**Comment by Sabbuth** [comment]
Hi FLo,

wie läuft alles? Der Phillip braucht auch noch Zeit um alles zu testen...

**Comment by flomaurer** [comment]
ich bin soweit fertig - hab alles hochgeladen und auch mal fehler behoben.
läuft jetzt.

**Comment by Sabbuth** [comment]
ok dann warten wir nur noch auf den Phillip :) funktioniert es überhaupt?

**Comment by flomaurer** [comment]
also compilen kann man es, jedoch konnt ic es noch nicht syntetisieren - synopsis nervt micht.
simulation hab ich nicht getestet, weil ja nix im speichersteht und auch noch kein clock_gen da ist.

**Comment by Phillip-W** [comment]
TB kommt heute hftl im laufe des tages 
ich schaus mir mal an wenn ich noch zeit hab
