### ISSUE TITLE
Prüfung

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/_entwurf_vhdl_prozessor_rtl#29]
Hi Jungs ich hätte eine Bitte und eine Frage zur Prüfung. Zuerst die Frage: Wann ist sie morgen und wo? Jetzt die Bitte: Ich musste plötzlich bei der Fragestunde weggehen, weil meine Freundin allergisch auf etwas reagiert. Deswegen weiß ich nicht, was ihr nach der ersten Aufgabe gemacht habt und möchte gerne ein Photo von den Seiten haben oder so was :)

**Comment by flomaurer** [comment]
Ich ha nix mitgeschrieben - ich glaub Philipp auch nicht.
War grad irgend eine Funktion schreiben, weiß ich aber nicht mehr.

Im Kalender hab ich 13:30 stehen. Raum wie immer. Ich komm so um 13:10 da hin.

**Comment by Phillip-W** [comment]
Mitgeschrieben hab ich auch nix.
Ecker hat nur gesagt, dass man verstehen sollte was verschiedene Bausteine bzw Funktionen sind, weil wir keine Zeit haben werden darüber nachzudenken.(Bsp Multiplizierer und resolving function)
Syntax Dinge sollte man griffbereit in den Aufzeichnungen haben, und sich am besten auskennen.

Wichtig ist nur, dass man immer auch Entitys/Packages schreibt wenn irgendwas gefragt ist was nicht alleine stehen kann.(bsp if braucht immer einen prozess)

Ich hab ehrlich gesagt noch garnix gemacht, außer Aufzeichnungen zusammen gesucht^^

P.S. Ist eine Open Book Klausur also kannst alles mitnehmen
