### ISSUE TITLE
BIT vs std_logic

### ISSUE THREAD

**Issue by Phillip-W** [Phillip-W/_entwurf_vhdl_prozessor_rtl#5]
Machen wir Bit oder std_logic?
Ich kann mich leider nicht erinnern ob der Herr Ecker was dazu gesagt hat.

**Comment by flomaurer** [comment]
kp.
also wenn wir std_logic machen, dann muss Patrick die shift nicht neu schreiben, die gibts schon.

**Comment by flomaurer** [comment]
also ich habs als bit_vector gemacht
